# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Faculta/IIIsem1/SCS/Lab/Lab4/ALU/ALU.cache/wt [current_project]
set_property parent.project_path D:/Faculta/IIIsem1/SCS/Lab/Lab4/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Faculta/IIIsem1/SCS/Lab/Lab4/ALU/ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Faculta/IIIsem1/SCS/Lab/Lab4/ALU/ALU.srcs/sources_1/new/FullAdder.vhd
  D:/Faculta/IIIsem1/SCS/Lab/Lab4/ALU/ALU.srcs/sources_1/new/WTree.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top WTree -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef WTree.dcp

catch { report_utilization -file WTree_utilization_synth.rpt -pb WTree_utilization_synth.pb }
